[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && gunicorn -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT app_local:app"
healthcheckPath = "/api/info"
healthcheckTimeout = 300
